# Inference containers use a Triton base container. (TRTOSS_VERSION) 22.02
# Training containers...
#  MR: Not applicable
#  TF: nvcr.io/nvidia/tensorflow:22.02-tf2-py3 (NVIDIA_TENSORFLOW_VERSION) 22.02-tf2, PYVER=3.8
#  PT: nvcr.io/nvidia/pytorch:21.12-py3 (NVIDIA_PYTORCH_VERSION) 22.02
"nvcr.io/nvidia/merlin/merlin-inference":
  "DGX":
    "span": True
  "DGX System":
    "field": "dgx_system"
  "Operating System":
    "field": "os"
  "NVIDIA Certified Systems":
    "span": True
  "NVIDIA Driver":
    "field": "nvidia_driver"
  "GPU Model":
    "field": "gpu_model"
  "Base Container Image":
    "span": True
  "Container Operating System":
    "field": "os"
  "Base Container":
    "field": "base_container"
  "CUDA":
    "field": "cuda"
  "RMM":
    "field": "rmm"
  "cuDF":
    "field": "cudf"
  "cuDNN":
    "field": "cudnn"
  "Merlin Core":
    "field": "merlin.core"
  "Merlin Models":
    "field": "merlin.models"
  "Merlin Systems":
    "field": "merlin.systems"
  "NVTabular":
    "field": "nvtabular"
  "Transformers4Rec":
    "field": "transformers4rec"
  "HugeCTR":
    "field": "hugectr"
  "SM":
    "field": "sm"
  "Triton Inference Server":
    "field": "triton"
  "Size":
    "field": "size"
---
"nvcr.io/nvidia/merlin/merlin-pytorch-inference":
  "DGX":
    "span": True
  "DGX System":
    "field": "dgx_system"
  "Operating System":
    "field": "os"
  "NVIDIA Certified Systems":
    "span": True
  "NVIDIA Driver":
    "field": "nvidia_driver"
  "GPU Model":
    "field": "gpu_model"
  "Base Container Image":
    "span": True
  "Container Operating System":
    "field": "os"
  "Base Container":
    "field": "base_container"
  "CUDA":
    "field": "cuda"
  "RMM":
    "field": "rmm"
  "cuDF":
    "field": "cudf"
  "cuDNN":
    "field": "cudnn"
  "Merlin Core":
    "field": "merlin.core"
  "Merlin Models":
    "field": "merlin.models"
  "Merlin Systems":
    "field": "merlin.systems"
  "NVTabular":
    "field": "nvtabular"
  "Transformers4Rec":
    "field": "transformers4rec"
  "HugeCTR":
    "field": "hugectr"
  "SM":
    "field": "sm"
  "PyTorch":
    "field": "pytorch"
  "Triton Inference Server":
    "field": "triton"
  "Size":
    "field": "size"
---
"nvcr.io/nvidia/merlin/merlin-pytorch-training":
  "DGX":
    "span": True
  "DGX System":
    "field": "dgx_system"
  "Operating System":
    "field": "os"
  "NVIDIA Certified Systems":
    "span": True
  "NVIDIA Driver":
    "field": "nvidia_driver"
  "GPU Model":
    "field": "gpu_model"
  "Base Container Image":
    "span": True
  "Container Operating System":
    "field": "os"
  "Base Container":
    "field": "base_container"
  "CUDA":
    "field": "cuda"
  "RMM":
    "field": "rmm"
  "cuDF":
    "field": "cudf"
  "cuDNN":
    "field": "cudnn"
  "Merlin Core":
    "field": "merlin.core"
  "Merlin Models":
    "field": "merlin.models"
  "Merlin Systems":
    "field": "merlin.systems"
  "NVTabular":
    "field": "nvtabular"
  "Transformers4Rec":
    "field": "transformers4rec"
  "HugeCTR":
    "field": "hugectr"
  "SM":
    "field": "sm"
  "PyTorch":
    "field": "pytorch"
  "Size":
    "field": "size"
---
"nvcr.io/nvidia/merlin/merlin-tensorflow-inference":
  "DGX":
    "span": True
  "DGX System":
    "field": "dgx_system"
  "Operating System":
    "field": "os"
  "NVIDIA Certified Systems":
    "span": True
  "NVIDIA Driver":
    "field": "nvidia_driver"
  "GPU Model":
    "field": "gpu_model"
  "Base Container Image":
    "span": True
  "Container Operating System":
    "field": "os"
  "Base Container":
    "field": "base_container"
  "CUDA":
    "field": "cuda"
  "RMM":
    "field": "rmm"
  "cuDF":
    "field": "cudf"
  "cuDNN":
    "field": "cudnn"
  "Merlin Core":
    "field": "merlin.core"
  "Merlin Models":
    "field": "merlin.models"
  "Merlin Systems":
    "field": "merlin.systems"
  "NVTabular":
    "field": "nvtabular"
  "Transformers4Rec":
    "field": "transformers4rec"
  "HugeCTR":
    "field": "hugectr"
  "SM":
    "field": "sm"
  "TensorFlow":
    "field": "tf"
  "Triton Inference Server":
    "field": "triton"
  "Size":
    "field": "size"
---
"nvcr.io/nvidia/merlin/merlin-tensorflow-training":
  "DGX":
    "span": True
  "DGX System":
    "field": "dgx_system"
  "Operating System":
    "field": "os"
  "NVIDIA Certified Systems":
    "span": True
  "NVIDIA Driver":
    "field": "nvidia_driver"
  "GPU Model":
    "field": "gpu_model"
  "Base Container Image":
    "span": True
  "Container Operating System":
    "field": "os"
  "Base Container":
    "field": "base_container"
  "CUDA":
    "field": "cuda"
  "RMM":
    "field": "rmm"
  "cuDF":
    "field": "cudf"
  "cuDNN":
    "field": "cudnn"
  "Merlin Core":
    "field": "merlin.core"
  "Merlin Models":
    "field": "merlin.models"
  "Merlin Systems":
    "field": "merlin.systems"
  "NVTabular":
    "field": "nvtabular"
  "Transformers4Rec":
    "field": "transformers4rec"
  "HugeCTR":
    "field": "hugectr"
  "SM":
    "field": "sm"
  "TensorFlow":
    "field": "tf"
  "Size":
    "field": "size"
---
"nvcr.io/nvidia/merlin/merlin-training":
  "DGX":
    "span": True
  "DGX System":
    "field": "dgx_system"
  "Operating System":
    "field": "os"
  "NVIDIA Certified Systems":
    "span": True
  "NVIDIA Driver":
    "field": "nvidia_driver"
  "GPU Model":
    "field": "gpu_model"
  "Base Container Image":
    "span": True
  "Container Operating System":
    "field": "os"
  "Base Container":
    "field": "base_container"
  "CUDA":
    "field": "cuda"
  "RMM":
    "field": "rmm"
  "cuDF":
    "field": "cudf"
  "cuDNN":
    "field": "cudnn"
  "Merlin Core":
    "field": "merlin.core"
  "Merlin Models":
    "field": "merlin.models"
  "Merlin Systems":
    "field": "merlin.systems"
  "NVTabular":
    "field": "nvtabular"
  "Transformers4Rec":
    "field": "transformers4rec"
  "HugeCTR":
    "field": "hugectr"
  "SM":
    "field": "sm"
  "Size":
    "field": "size"

