name: docs-smx-data

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.8]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Ubuntu packages
        run: |
          sudo apt-get update -y
          sudo apt-get clean autoclean
          sudo apt-get autoremove --yes
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools==59.4.0 wheel
          python -m pip install -r docs/requirements-doc.txt
      - name: Maximize disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
      - name: Get container data
        run: |
          python docs/extractor.py
      - name: Initialize Git configuration
        run: |
          git config user.name docs-smx-bot
          git config user.email do-not-send-@github.com
      - name: Commit updates to data.json
        run: |
          x=$(git status --porcelain)
          if grep -q "data.json" <<< "${x}"; then
            git add .
            git commit -m 'Updates from new containers'
            git push
          fi
