name: GPU CI

on:
  workflow_dispatch:
  push:
    branches: 
      - main
      - "pull-request/[0-9]+"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  gpu-ci:
    runs-on: linux-amd64-gpu-p100-latest-1
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Run tests
      run: |
        ref_type=${{ github.ref_type }}
        branch=main
        if [[ $ref_type == "tag"* ]]
        then
          raw=$(git branch -r --contains ${{ github.ref_name }})
          branch=${raw/origin\/}
        fi
        cd ${{ github.workspace }}; tox -e test-gpu -- $branch

  gpu-ci-multigpu:
    runs-on: 2GPU
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Run tests
      run: |
        ref_type=${{ github.ref_type }}
        branch=main
        if [[ $ref_type == "tag"* ]]
        then
          raw=$(git branch -r --contains ${{ github.ref_name }})
          branch=${raw/origin\/}
        fi
        cd ${{ github.workspace }}; tox -e test-gpu-multigpu -- $branch
